language: c
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.8"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - source $TRAVIS_BUILD_DIR/install.sh
script:
  - arduino --verify PressureSensor.ino
